# node-api-gateway/Dockerfile.node

FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code (index.js)
COPY . .

# Expose the port
EXPOSE 3001

# Command to run the application
CMD [ "npm", "start" ]