# -*- coding: utf-8 -*-
"""satellite_fsm.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qaMRcsL7SLkGgW-EWfL3oiTrV997z7RC
"""

#---importing libraries---
#---01---Orbital mechanics layer---
import numpy as np
from typing import Dict, Callable
from numpy.polynomial.hermite import hermval
from scipy.stats import norm
from astropy import units as u
from astropy.time import Time
from poliastro.bodies import Earth
from poliastro.twobody import Orbit
from poliastro.maneuver import Maneuver
from poliastro.iod import izzo
import numpy as np
import matplotlib.pyplot as plt
from tabulate import tabulate
import pandas as pd
#---02---Sensor Suite---
import torch
import torch.nn as nn
import numpy as np
from scipy.spatial.transform import Rotation as R

#---03---Satellite State Machine---
import json

#---03---
#---Satellite State Machine---

'''{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Satellite FSM Schema",
  "type": "object",
  "properties": {
    "states": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["NOMINAL", "SAFE_MODE", "LOW_POWER", "COMM_LOSS", "ANOMALY"]
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "initial_state": {
      "type": "string",
      "enum": ["NOMINAL", "SAFE_MODE", "LOW_POWER", "COMM_LOSS", "ANOMALY"]
    },
    "subsystems": {
      "type": "object",
      "properties": {
        "Power": {
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "enum": ["OK", "LOW", "FAIL", "ANOMALY"]
            }
          },
          "required": ["status"]
        },
        "Thermal": {
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "enum": ["OK", "WARNING", "CRITICAL", "ANOMALY"]
            }
          },
          "required": ["status"]
        },
        "Communication": {
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "enum": ["OK", "LOSS", "DEGRADED", "ANOMALY"]
            }
          },
          "required": ["status"]
        },
        "ADCS": {
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "enum": ["OK", "DEGRADED", "FAIL", "ANOMALY"]
            }
          },
          "required": ["status"]
        },
        "Payload": {
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "enum": ["IDLE", "ACTIVE", "FAIL", "ANOMALY"]
            }
          },
          "required": ["status"]
        },
        "Propulsion": {
          "type": "object",
          "properties": {
            "status": {
              "type": "string",
              "enum": ["READY", "FIRING", "FAIL", "ANOMALY"]
            }
          },
          "required": ["status"]
        }
      },
      "required": ["Power", "Thermal", "Communication", "ADCS", "Payload", "Propulsion"]
    },
    "transitions": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "from": {
            "type": "string",
            "enum": ["NOMINAL", "SAFE_MODE", "LOW_POWER", "COMM_LOSS", "ANOMALY", "ANY"]
          },
          "to": {
            "type": "string",
            "enum": ["NOMINAL", "SAFE_MODE", "LOW_POWER", "COMM_LOSS", "ANOMALY"]
          },
          "conditions": {
            "type": "array",
            "items": {
              "type": "string",
              "pattern": "^[A-Za-z]+\\.status\\s*==\\s*'[^']+'$"
            },
            "minItems": 1
          }
        },
        "required": ["from", "to", "conditions"]
      },
      "minItems": 1
    }
  },
  "required": ["states", "initial_state", "subsystems", "transitions"]
}



#--------

{
  "states": ["NOMINAL", "SAFE_MODE", "LOW_POWER", "COMM_LOSS", "ANOMALY"],
  "initial_state": "NOMINAL",
  "subsystems": {
    "Power": {"status": "OK"},
    "Thermal": {"status": "OK"},
    "Communication": {"status": "OK"},
    "ADCS": {"status": "OK"},
    "Payload": {"status": "IDLE"},
    "Propulsion": {"status": "READY"}
  },
  "transitions": [
    {
      "from": "NOMINAL",
      "to": "SAFE_MODE",
      "conditions": ["Power.status == 'FAIL'", "Thermal.status == 'CRITICAL'"]
    },
    {
      "from": "NOMINAL",
      "to": "LOW_POWER",
      "conditions": ["Power.status == 'LOW'"]
    },
    {
      "from": "NOMINAL",
      "to": "COMM_LOSS",
      "conditions": ["Communication.status == 'LOSS'"]
    },
    {
      "from": "SAFE_MODE",
      "to": "NOMINAL",
      "conditions": ["Power.status == 'OK'", "Thermal.status == 'OK'"]
    },
    {
      "from": "COMM_LOSS",
      "to": "NOMINAL",
      "conditions": ["Communication.status == 'OK'"]
    },
    {
      "from": "ANY",
      "to": "ANOMALY",
      "conditions": [
        "Power.status == 'ANOMALY'",
        "Thermal.status == 'ANOMALY'",
        "Communication.status == 'ANOMALY'",
        "ADCS.status == 'ANOMALY'",
        "Payload.status == 'ANOMALY'",
        "Propulsion.status == 'ANOMALY'"
      ]
    }
  ]
}

#------'''



import json

class SatelliteFSM:
    def __init__(self, fsm_json):
        self.fsm = json.loads(fsm_json)
        self.state = self.fsm['initial_state']
        self.subsystems = self.fsm['subsystems']
        self.transitions = self.fsm['transitions']

    def update_subsystem_status(self, subsystem, status):
        if subsystem in self.subsystems:
            self.subsystems[subsystem]['status'] = status
        else:
            raise ValueError(f"Unknown subsystem '{subsystem}'")

    def _eval_condition(self, condition):
        # condition example: "Power.status == 'FAIL'"
        left, right = condition.split("==")
        left = left.strip()
        right = right.strip().strip("'\"")

        subsystem, attr = left.split('.')
        current_value = self.subsystems.get(subsystem, {}).get(attr, None)
        return current_value == right

    def _check_conditions(self, conditions, is_any=False):
        if self.state == "ANOMALY":
            return False
        if is_any:
            return any(self._eval_condition(c) for c in conditions)
        else:
            return all(self._eval_condition(c) for c in conditions)

    def step(self):
        for t in self.transitions:
            is_any = (t['from'] == "ANY")
            if t['from'] == self.state or is_any:
                if self._check_conditions(t['conditions'], is_any):
                    print(f"Transitioning from {self.state} to {t['to']} on conditions {t['conditions']}")
                    self.state = t['to']
                    break

    def status(self):
        return {
            "state": self.state,
            "subsystems": self.subsystems
        }

# === Example usage ===
if __name__ == "__main__":
    fsm_config = '''
    {
      "states": ["NOMINAL", "SAFE_MODE", "LOW_POWER", "COMM_LOSS", "ANOMALY"],
      "initial_state": "NOMINAL",
      "subsystems": {
        "Power": {"status": "OK"},
        "Thermal": {"status": "OK"},
        "Communication": {"status": "OK"},
        "ADCS": {"status": "OK"},
        "Payload": {"status": "IDLE"},
        "Propulsion": {"status": "READY"}
      },
      "transitions": [
        {
          "from": "NOMINAL",
          "to": "SAFE_MODE",
          "conditions": ["Power.status == 'FAIL'", "Thermal.status == 'CRITICAL'"]
        },
        {
          "from": "NOMINAL",
          "to": "LOW_POWER",
          "conditions": ["Power.status == 'LOW'"]
        },
        {
          "from": "NOMINAL",
          "to": "COMM_LOSS",
          "conditions": ["Communication.status == 'LOSS'"]
        },
        {
          "from": "SAFE_MODE",
          "to": "NOMINAL",
          "conditions": ["Power.status == 'OK'", "Thermal.status == 'OK'"]
        },
        {
          "from": "COMM_LOSS",
          "to": "NOMINAL",
          "conditions": ["Communication.status == 'OK'"]
        },
        {
          "from": "ANY",
          "to": "ANOMALY",
          "conditions": [
            "Power.status == 'ANOMALY'",
            "Thermal.status == 'ANOMALY'",
            "Communication.status == 'ANOMALY'",
            "ADCS.status == 'ANOMALY'",
            "Payload.status == 'ANOMALY'",
            "Propulsion.status == 'ANOMALY'"
          ]
        }
      ]
    }
    '''

    fsm = SatelliteFSM(fsm_config)

    print("Initial state:", fsm.status())

    # Simulate Power going low
    fsm.update_subsystem_status("Power", "LOW")
    fsm.step()
    print("After Power LOW:", fsm.status())

    # Simulate Power back to OK
    fsm.update_subsystem_status("Power", "OK")
    fsm.step()
    print("After Power OK:", fsm.status())

    # Simulate anomaly
    fsm.update_subsystem_status("ADCS", "ANOMALY")
    fsm.step()
    print("After ADCS ANOMALY:", fsm.status())