# -*- coding: utf-8 -*-
"""simulator_models.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WZpAy_y0WM4Mh8ny2amPmn47eKoVyJKN
"""

#---importing libraries---
#---01---Orbital mechanics layer---
import numpy as np
from typing import Dict, Callable
from numpy.polynomial.hermite import hermval
from scipy.stats import norm
from astropy import units as u
from astropy.time import Time
from poliastro.bodies import Earth
from poliastro.twobody import Orbit
from poliastro.maneuver import Maneuver
from poliastro.iod import izzo
import numpy as np
import matplotlib.pyplot as plt
from tabulate import tabulate
import pandas as pd
#---02---Sensor Suite---
import torch
import torch.nn as nn
import numpy as np
from scipy.spatial.transform import Rotation as R

#---03---Satellite State Machine---
import json

# --- 01 ---
# --- Orbital Mechanics Layer/Class ---


class OrbitSimulator:
    def __init__(self, epoch="2025-07-17 00:00:00", altitude_km=500, inclination_deg=51.6):
        self.epoch = Time(epoch, scale='utc')
        self.altitude = altitude_km * u.km
        self.inclination = inclination_deg * u.deg # New: Store inclination
        self.orbit = self._init_orbit()
        self.current_time_step = 0
        self._cumulative_alt_drift = 0.0
        print(f"[Init] Orbit created at {altitude_km} km with inclination {inclination_deg}°")
        # NOTE: If you are re-using an OrbitSimulator instance, you should
        # manually call .reset() on all sensor instances passed to step_simulation.

    def _init_orbit(self):
        # Calculate semi-major axis (a) from altitude
        a = Earth.R + self.altitude
        
        # To define inclination, we must use from_classical instead of circular().
        # We define a circular orbit using placeholder angles for RAAN, Argument of Perigee, and True Anomaly.
        
        # CRITICAL FIX: Setting the True Anomaly (last argument) to 90 * u.deg 
        # ensures the orbit starts at the point of maximum latitude (equal to inclination).
        return Orbit.from_classical(
            Earth,
            a,
            0 * u.one, # eccentricity (e)
            self.inclination, # inclination (i)
            0 * u.deg, # Right Ascension of the Ascending Node (RAAN)
            0 * u.deg, # Argument of Perigee
            90 * u.deg, # True Anomaly (starting point at max latitude)
            epoch=self.epoch
        )

    def propagate(self, duration_minutes=90):
        tof = duration_minutes * u.min
        propagated = self.orbit.propagate(tof)
        return propagated

    def apply_maneuver(self, dv_vector):
        """Apply instantaneous maneuver (ΔV vector in km/s)"""
        dv = Maneuver.impulse(dv_vector * u.km / u.s)
        self.orbit = self.orbit.apply_maneuver(dv)
        # --- FIX: Update the stored inclination attribute with the new value
        self.inclination = self.orbit.inc.to(u.deg) 
        print(f"[Maneuver] Applied ΔV: {dv_vector} km/s")

    def solve_lambert(self, target_r, tof_minutes):
        r1 = self.orbit.r
        r2 = target_r * u.km
        tof = tof_minutes * u.min
        v0, v1 = izzo.lambert(Earth.k, r1, r2, tof)
        print("[Lambert] Computed transfer velocities.")
        return v0, v1

    def monte_carlo_sample(self, samples=1000, pce_order=3):
        """
        Generates Monte Carlo samples and fits PCE to the resulting orbital period
        uncertainty based on initial position/velocity perturbations.
        """

        def orbital_period_model(params):
            """Calculates the orbital period for a perturbed orbit."""
            pos_perturb = 1 + params.get("pos_perturb", 0)
            vel_perturb = 1 + params.get("vel_perturb", 0)

            perturbed_r = self.orbit.r * pos_perturb
            perturbed_v = self.orbit.v * vel_perturb

            perturbed_orbit = Orbit.from_vectors(Earth, perturbed_r, perturbed_v, epoch=self.epoch)

            # Return the period (a scalar) in minutes
            return perturbed_orbit.period.to(u.min).value

        param_distributions = {
            "pos_perturb": {"mean": 0.0, "std": 0.001, "type": "normal"},
            "vel_perturb": {"mean": 0.0, "std": 0.001, "type": "normal"},
        }

        # Use the scalar model
        propagator = UncertaintyPropagator(
            param_distributions=param_distributions,
            model_fn=orbital_period_model,
            pce_order=pce_order,
            num_samples=samples
        )

        propagator.sample_inputs()
        propagator.run_monte_carlo()
        propagator.fit_pce()

        return propagator

    def predict_pce(self, param_name: str):
        """
        Return the PCE prediction for a given parameter
        """
        dist = self.param_distributions[param_name]
        ξ = np.array([(s[param_name] - dist["mean"]) / dist["std"] for s in self.sampled_inputs])
        basis = [ξ**i for i in range(self.pce_order + 1)]
        basis_matrix = np.stack(basis, axis=1)
        return basis_matrix @ self.pce_coeffs[param_name]

    def summary(self):
        """
        Return high-level stats
        """
        return {
            "monte_carlo_mean": np.mean(self.mc_outputs),
            "monte_carlo_std": np.std(self.mc_outputs),
            "samples": self.num_samples,
            "pce_order": self.pce_order,
            "param_names": list(self.param_distributions.keys())
        }

    def get_geographic_position(self):
        """
        Converts the current ECI position (r_km) to Latitude and Longitude (Geographic).
        
        Returns:
            (lat_deg, lon_deg): Tuple of geographic coordinates.
        """
        # ECI position vector in km
        r_eci = self.orbit.r.to(u.km).value
        
        # Calculate Julian Date and Greenwich Mean Sidereal Time (GMST)
        jd = self.orbit.epoch.jd
        T_ut1 = (jd - 2451545.0) / 36525.0
        
        # Approximate GMST in degrees (standard formula, good for visualization)
        gmst_deg = 100.46061837 + 36000.770053608 * T_ut1 + 0.00038793 * T_ut1**2
        gmst_rad = np.deg2rad(gmst_deg)
        
        # Calculate Earth-Centered Fixed (ECF) position (rotating the ECI frame)
        # Rotation matrix Rz(-GMST)
        cos_gmst = np.cos(gmst_rad)
        sin_gmst = np.sin(gmst_rad)
        
        # r_ecf = Rz(-gmst) * r_eci
        x_ecf = r_eci[0] * cos_gmst + r_eci[1] * sin_gmst
        y_ecf = r_eci[1] * cos_gmst - r_eci[0] * sin_gmst
        z_ecf = r_eci[2]
        
        r_ecf = np.array([x_ecf, y_ecf, z_ecf])
        
        # Convert ECF (Cartesian) to Geographic (Spherical)
        r_mag = np.linalg.norm(r_ecf)
        
        # Latitude 
        lat_rad = np.arcsin(z_ecf / r_mag)
        lat_deg = np.rad2deg(lat_rad)
        
        # Longitude 
        lon_rad = np.arctan2(y_ecf, x_ecf)
        lon_deg = np.rad2deg(lon_rad)
        
        # Normalize longitude to -180 to 180
        lon_deg = (lon_deg + 180) % 360 - 180
            
        return lat_deg, lon_deg

    def plot(self):
        ax = self.orbit.plot()
        plt.title("Orbit in LEO")
        plt.grid(True)
        plt.show()


    def step_simulation(self, sensor_suite, fsm, steps_s=5):
        """
        Propagates the orbit using the stable Keplerian model and adds artificial drift.
        """
        # 1. Propagate Orbit (Propagate only by the step time, then update the state)
        tof_step = steps_s * u.s
        propagated_orbit = self.orbit.propagate(tof_step)
        self.orbit = propagated_orbit

        self.current_time_step += steps_s
        current_time = self.orbit.epoch

        r_km = propagated_orbit.r.to(u.km).value
        r_m = r_km * 1000
        r_mag = np.linalg.norm(r_km)

        # Calculate Geographic Position (NEW)
        lat_deg, lon_deg = self.get_geographic_position()

        # Get the true current inclination from the poliastro orbit object
        true_inclination_deg = self.orbit.inc.to(u.deg).value # <-- New line

        # Introduce a small, non-physical drift to simulate minimal changes
        instant_drift_km = np.random.uniform(-0.0005, 0.0005)
        self._cumulative_alt_drift += instant_drift_km

        base_altitude_km = r_mag - Earth.R.to(u.km).value
        # Add the cumulative drift to the constant altitude value
        altitude_km_value = round(base_altitude_km + self._cumulative_alt_drift, 3)

        # Placeholders for constant true values
        TRUE_SUN_VECTOR = np.array([0.5, 0.5, 0.707])
        TRUE_MAG_FIELD = np.array([20e-6, 10e-6, -40e-6])
        TRUE_TEMP = 35.0
        TRUE_ATTITUDE = np.array([0.0, 0.0, 0.0, 1.0])

        entry = {
            "time_s": self.current_time_step,
            "timestamp_utc": current_time.utc.iso.replace(" ", "T") + "Z",
            "position_km_true": [round(x, 3) for x in r_km],
            "altitude_km": altitude_km_value,
            # NEW TELEMETRY FIELDS
            "latitude_deg": round(lat_deg, 3), 
            "longitude_deg": round(lon_deg, 3),
            "inclination_deg": round(true_inclination_deg, 3), # <-- Log the true current inclination
        }

        # 2. Sensor Steps (Capturing all outputs)

        # GPS: Capture 3D vector and calculate error
        measured_gps_pos = sensor_suite["gps"].step(r_m)
        entry["gps_measured_position_m"] = [round(x, 2) for x in measured_gps_pos]
        entry["gps_error_m"] = round(np.linalg.norm(measured_gps_pos - r_m), 2)

        # ADCS/Thermal Sensors
        entry["st_quat"] = [round(x, 4) for x in sensor_suite["star_tracker"].step(TRUE_ATTITUDE)]
        entry["mag_vec_measured"] = [round(x, 9) for x in sensor_suite["magnetometer"].step(TRUE_MAG_FIELD)]
        entry["sun_vec_measured"] = [round(x, 3) for x in sensor_suite["sun_sensor"].step(TRUE_SUN_VECTOR)]
        entry["ir_temp_measured"] = round(sensor_suite["ir_sensor"].step(TRUE_TEMP), 2)

        # Comms and Power Subsystems (ALL keys are logged via .update)
        comms_data = sensor_suite["comms"].step()
        power_data = sensor_suite["power"].step()

        entry.update(comms_data)
        entry.update(power_data)

        # 3. FSM Update
        fsm.update_subsystem_status("Power", "LOW" if power_data["soc"] < 0.3 else "OK")
        fsm.update_subsystem_status("Thermal", "CRITICAL" if entry["ir_temp_measured"] > 40 else "OK")
        fsm.update_subsystem_status("Communication", "LOSS" if comms_data["PacketLoss"] > 0.5 else "OK")
        fsm.step()
        entry["fsm_state"] = fsm.state

        return entry

class UncertaintyPropagator:
    """
    Propagates uncertainty using Monte Carlo sampling and Polynomial Chaos Expansion (PCE).
    Useful for synthetic sensor drift, system errors, and mission variability modeling.
    """

    def __init__(self,
                 param_distributions: Dict[str, Dict],
                 model_fn: Callable[[Dict[str, float]], float],
                 pce_order: int = 2,
                 num_samples: int = 1000):
        """
        Parameters:
        - param_distributions: Dict of input parameters with distribution metadata
          e.g. {"sensor_noise_std": {"mean": 0.01, "std": 0.005, "type": "normal"}}
        - model_fn: Function that takes parameter dict and returns model output (scalar or vector)
        - pce_order: Order of Hermite PCE (for Gaussian)
        - num_samples: Number of Monte Carlo samples
        """
        self.param_distributions = param_distributions
        self.model_fn = model_fn
        self.pce_order = pce_order
        self.num_samples = num_samples

        self.sampled_inputs = []
        self.mc_outputs = []
        self.pce_coeffs = {}

    def sample_inputs(self):
        """
        Sample from defined parameter distributions using Monte Carlo
        """
        samples = []
        for _ in range(self.num_samples):
            sample = {}
            for name, dist in self.param_distributions.items():
                if dist["type"] == "normal":
                    sample[name] = np.random.normal(loc=dist["mean"], scale=dist["std"])
                else:
                    raise NotImplementedError(f"Dist {dist['type']} not supported.")
            samples.append(sample)
        self.sampled_inputs = samples

    def run_monte_carlo(self):
        """
        Run Monte Carlo simulation using sampled inputs
        """
        self.mc_outputs = [self.model_fn(sample) for sample in self.sampled_inputs]

    def fit_pce(self):
        """
        Fit Hermite Polynomial Chaos Expansion to the Monte Carlo data
        """
        for name, dist in self.param_distributions.items():
            ξ = np.array([(s[name] - dist["mean"]) / dist["std"] for s in self.sampled_inputs])
            basis = [ξ**i for i in range(self.pce_order + 1)]
            basis_matrix = np.stack(basis, axis=1)

            y = np.array(self.mc_outputs)
            coeffs, _, _, _ = np.linalg.lstsq(basis_matrix, y, rcond=None)
            self.pce_coeffs[name] = coeffs

    def predict_pce(self, param_name: str):
        """
        Return the PCE prediction for a given parameter
        """
        dist = self.param_distributions[param_name]
        ξ = np.array([(s[param_name] - dist["mean"]) / dist["std"] for s in self.sampled_inputs])
        basis = [ξ**i for i in range(self.pce_order + 1)]
        basis_matrix = np.stack(basis, axis=1)
        return basis_matrix @ self.pce_coeffs[param_name]

    def summary(self):
        """
        Return high-level stats
        """
        return {
            "monte_carlo_mean": np.mean(self.mc_outputs),
            "monte_carlo_std": np.std(self.mc_outputs),
            "samples": self.num_samples,
            "pce_order": self.pce_order,
            "param_names": list(self.param_distributions.keys())
        }

#---02---
#---Sensor Layer---

#---NN Based Drift GRU Module---
class DriftGRU(nn.Module):
    def __init__(self, input_size=3, hidden_size=16, output_size=None, num_layers=1):
        super().__init__()
        self.input_size = input_size
        self.output_size = output_size if output_size is not None else input_size
        self.gru = nn.GRU(input_size, hidden_size, num_layers)
        self.linear = nn.Linear(hidden_size, self.output_size)
        self.hidden = None
        
        # FIX: Initialize the linear layer's weights/biases to near zero 
        # to prevent explosive drift when the model is untrained.
        torch.nn.init.zeros_(self.linear.weight)
        if self.linear.bias is not None:
            torch.nn.init.zeros_(self.linear.bias)

    def forward(self, x):
        # x shape: (seq_len=1, batch=1, input_size)
        out, self.hidden = self.gru(x, self.hidden)
        drift = self.linear(out[-1])
        return drift

    def reset_hidden(self):
        self.hidden = None
#---Star Tracker Class---
class StarTrackerML:
    def __init__(self, noise_std_deg=0.01, dt=1.0, device='cpu'):
        self.noise_std_rad = np.deg2rad(noise_std_deg)
        self.dt = dt

        self.device = device
        self.model = DriftGRU().to(self.device)
        self.model.reset_hidden()

        self.bias = torch.zeros(3, device=self.device)  # Bias in radians

    def step(self, true_attitude_quat):
        # Prepare input (previous bias) for model
        input_tensor = self.bias.view(1, 1, 3)  # seq_len=1, batch=1, features=3

        # Predict drift delta from GRU model
        drift_delta = self.model(input_tensor).view(-1)  # shape (3,)

        # Update bias
        self.bias = self.bias + drift_delta

        # Add Gaussian noise (numpy, converted to torch)
        noise = torch.tensor(np.random.normal(0, self.noise_std_rad, 3), device=self.device, dtype=torch.float32)

        error_vec = self.bias + noise

        error_angle = torch.norm(error_vec).item()
        if error_angle > 1e-8:
            axis = error_vec / error_angle
            # Use scipy Rotation for quaternion conversion
            delta_q = R.from_rotvec(axis.cpu().detach().numpy() * error_angle).as_quat()
        else:
            delta_q = np.array([0, 0, 0, 1])

        # Quaternion multiplication
        r_true = R.from_quat(true_attitude_quat)
        r_error = R.from_quat(delta_q)
        r_measured = r_error * r_true

        return r_measured.as_quat()
    
    def reset(self):
        """Resets the internal bias and the GRU's hidden state."""
        self.bias = torch.zeros(3, device=self.device)
        self.model.reset_hidden()
    


#---ML Based GPS Sensor---

class GPSML:
    def __init__(self, noise_std_m=0.5, dt=1.0, device='cpu'):
        """
        Parameters:
        - noise_std_m: Gaussian noise standard deviation in meters
        - dt: time step in seconds
        """
        self.noise_std = noise_std_m
        self.dt = dt
        self.device = device

        self.bias = np.zeros(3)  # initial position bias in meters

        # ML drift model
        self.drift_model = DriftGRU().to(device)
        self.drift_model.reset_hidden()
        self.drift_model.eval()

    def step(self, true_position):
        """
        Input:
        - true_position: numpy array shape (3,) in meters

        Output:
        - measured_position: numpy array shape (3,) in meters
        """
        bias_input = torch.tensor(self.bias, dtype=torch.float32, device=self.device).view(1,1,-1)

        with torch.no_grad():
            bias_drift_tensor = self.drift_model(bias_input)

        bias_drift = bias_drift_tensor.cpu().numpy().flatten() * self.dt

        self.bias += bias_drift

        noise = np.random.normal(0, self.noise_std, size=3)

        measured_position = true_position + self.bias + noise
        return measured_position

    def reset(self):
        self.bias = np.zeros(3)
        self.drift_model.reset_hidden()

#---ML Based Sun Sensor---

class SunSensorML:
    def __init__(self, noise_std_deg=0.2, dt=1.0, device='cpu'):
        self.noise_std_rad = np.deg2rad(noise_std_deg)
        self.dt = dt
        self.device = device

        self.bias = np.zeros(3)  # small angle rotational bias vector (rad)
        self.drift_model = DriftGRU().to(device)
        self.drift_model.eval()
        self.drift_model.reset_hidden()

    def step(self, true_sun_vector):
        """
        Input:
        - true_sun_vector: numpy array shape (3,), unit vector

        Returns:
        - measured_sun_vector: numpy array shape (3,), unit vector with ML noise
        """
        # Drift from ML model
        input_tensor = torch.tensor(self.bias, dtype=torch.float32, device=self.device).view(1, 1, -1)
        with torch.no_grad():
            drift_increment = self.drift_model(input_tensor).cpu().numpy().flatten()

        self.bias += drift_increment * self.dt

        # Gaussian noise
        noise = np.random.normal(0, self.noise_std_rad, size=3)

        # Total error rotation vector
        total_error = self.bias + noise

        angle = np.linalg.norm(total_error)
        if angle > 1e-8:
            axis = total_error / angle
            rot = R.from_rotvec(axis * angle)
        else:
            rot = R.identity()

        measured_vector = rot.apply(true_sun_vector)
        return measured_vector / np.linalg.norm(measured_vector)  # ensure unit vector

    def reset(self):
        self.bias = np.zeros(3)
        self.drift_model.reset_hidden()

#---ML Based IR Sensor---

class IRSensorML:
    def __init__(self, noise_std=0.05, dt=1.0, device='cpu'):
        self.noise_std = noise_std
        self.dt = dt
        self.device = device

        self.bias = 0.0
        self.drift_model = DriftGRU(input_size=1).to(device)
        self.drift_model.eval()
        self.drift_model.reset_hidden()

    def step(self, true_temp):
        """
        Input:
        - true_temp: scalar (e.g., temperature in arbitrary units)
        Returns:
        - measured_temp: scalar with ML noise
        """
        input_tensor = torch.tensor([[ [self.bias] ]], dtype=torch.float32, device=self.device)
        with torch.no_grad():
            # The GRU's now zero-initialized weights will keep this drift small initially
            drift_increment = self.drift_model(input_tensor).cpu().numpy().flatten()[0]

        self.bias += drift_increment * self.dt
        noise = np.random.normal(0, self.noise_std)
        measured_temp = true_temp + self.bias + noise
        return measured_temp

    def reset(self):
        self.bias = 0.0
        self.drift_model.reset_hidden()
#---ML Based Magneto Meter Sensor---

class MagnetometerML:
    def __init__(self, noise_std=50e-9, dt=1.0, device='cpu'):  # Tesla units, 50 nT std dev
        self.noise_std = noise_std
        self.dt = dt
        self.device = device

        self.bias = np.zeros(3)
        self.drift_model = DriftGRU(input_size=3).to(device)
        self.drift_model.eval()
        self.drift_model.reset_hidden()

    def step(self, true_field_vector):
        """
        Input:
        - true_field_vector: numpy array shape (3,) representing magnetic field in Tesla

        Returns:
        - measured_field_vector: numpy array shape (3,) with ML-based noise and drift
        """
        input_tensor = torch.tensor(self.bias, dtype=torch.float32, device=self.device).view(1, 1, -1)

        with torch.no_grad():
            drift_increment = self.drift_model(input_tensor).cpu().numpy().flatten()

        self.bias += drift_increment * self.dt
        noise = np.random.normal(0, self.noise_std, size=3)

        measured = true_field_vector + self.bias + noise
        return measured

    def reset(self):
        self.bias = np.zeros(3)
        self.drift_model.reset_hidden()

class CommunicationSubsystem:
    def __init__(self, dt=1.0):
        self.dt = dt  # Time step in seconds

        # Base stats
        self.base_snr_db = 20.0       # Ideal SNR in dB
        self.base_freq_offset_hz = 0.0
        self.base_packet_loss = 0.01  # 1% base loss

        # Internal ML-like drift state (mocked RNN-like)
        self.hidden_state = np.random.randn(3) * 0.001  # small random init

        # Drift/bias accumulators
        self.snr_drift = 0.0
        self.freq_drift = 0.0
        self.loss_drift = 0.0

    def _ml_drift_model(self):
        # Simple fake RNN update (you can replace this with a real ML model)
        # Simulates long-term memory behavior
        input_noise = np.random.normal(0, 0.01, size=3)
        self.hidden_state = 0.9 * self.hidden_state + 0.1 * input_noise

        # Simulated learned bias/drift outputs
        snr_bias = self.hidden_state[0] * 5    # Drift up/down ±0.5 dB
        freq_bias = self.hidden_state[1] * 50  # Drift ±50 Hz
        loss_bias = self.hidden_state[2] * 0.01  # Drift ±1%

        return snr_bias, freq_bias, loss_bias

    def step(self):
        # ML bias/drift
        snr_bias, freq_bias, loss_bias = self._ml_drift_model()

        # Add random noise
        snr_noise = np.random.normal(0, 0.3)
        freq_noise = np.random.normal(0, 5)
        loss_noise = np.random.normal(0, 0.002)

        # Final simulated values
        snr = self.base_snr_db + snr_bias + snr_noise
        freq_offset = self.base_freq_offset_hz + freq_bias + freq_noise
        packet_loss = np.clip(self.base_packet_loss + loss_bias + loss_noise, 0.0, 1.0)

        return {
            "SNR_dB": snr,
            "FrequencyOffset_Hz": freq_offset,
            "PacketLoss": packet_loss
        }
    def reset(self):
        """Resets the communication subsystem's drift state."""
        self.hidden_state = np.random.randn(3) * 0.001
        self.snr_drift = 0.0
        self.freq_drift = 0.0
        self.loss_drift = 0.0
    


#---Power Subsystem Sensors---

class PowerSubsystem:
    def __init__(self, dt=1.0):
        self.dt = dt  # seconds

        # True system state (simulate charging/discharging)
        self.solar_voltage = 28.0  # volts
        self.solar_current = 1.5   # amps
        self.battery_voltage = 24.0
        self.battery_current = -0.5  # discharging
        self.battery_temp = 25.0
        self.soc = 0.80  # 80%

        # Drift models
        self.solar_drift = DriftGRU(input_size=1, output_size=1)
        self.battery_drift = DriftGRU(input_size=1, output_size=1)
        self.optimizer = torch.optim.Adam(
            list(self.solar_drift.parameters()) + list(self.battery_drift.parameters()), lr=0.01
        )

    def step(self):
        # Simulate solar panel fluctuations (like orbital shadow)
        irradiance_factor = np.sin(np.random.uniform(0, np.pi))  # 0 to 1
        self.solar_voltage = 28.0 * irradiance_factor
        self.solar_current = 1.5 * irradiance_factor

        # Update battery based on charge input
        net_charge = self.solar_current - 1.0  # assume 1A base load
        self.battery_current = net_charge
        self.soc += net_charge * self.dt / 3600  # in Amp-hours, crude approx
        self.soc = np.clip(self.soc, 0.0, 1.0)

        self.battery_voltage = 22.0 + 2.0 * self.soc  # crude mapping
        self.battery_temp += np.random.normal(0, 0.05)

        # Create tensor inputs for GRU
        t_solar = torch.tensor([[[self.solar_voltage]]], dtype=torch.float32)
        t_batt = torch.tensor([[[self.battery_voltage]]], dtype=torch.float32)

        with torch.no_grad():
            drift_solar = self.solar_drift(t_solar).item()
            drift_batt = self.battery_drift(t_batt).item()

        return {
            "solar_voltage": self.solar_voltage + drift_solar,
            "solar_current": self.solar_current + np.random.normal(0, 0.02),
            "battery_voltage": self.battery_voltage + drift_batt,
            "battery_current": self.battery_current + np.random.normal(0, 0.02),
            "battery_temp": self.battery_temp,
            "soc": self.soc
        }
    def reset(self):
        """Resets the power subsystem's GRU hidden states and nominal values."""
        self.solar_drift.reset_hidden()
        self.battery_drift.reset_hidden()
        # Reset state to nominal values for a fresh run
        self.soc = 0.80
        self.battery_temp = 25.0 # <--- Ensure battery temp is reset to 25.0
        self.solar_voltage = 28.0
        self.solar_current = 1.5
        self.battery_voltage = 24.0
        self.battery_current = -0.5